apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: talos-node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: talos-node-exporter
  template:
    metadata:
      labels:
        app: talos-node-exporter
    spec:
      serviceAccountName: talos-node-exporter
      containers:
        - name: talos-node-exporter
          image: ghcr.io/siderolabs/talos-node-exporter:v1.9.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9100
              name: metrics
          resources:
            requests:
              cpu: 15m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: talos-node-exporter
  namespace: monitoring
  labels:
    app: talos-node-exporter
spec:
  selector:
    app: talos-node-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics