apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2025-10-07T17:52:37.7778833+02:00"
  creationTimestamp: "2025-10-05T12:17:22Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 5
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: infra
  namespace: flux-system
  resourceVersion: "3296613"
  uid: 1f6d342d-20fa-4464-af44-1f7b39faa6c4
spec:
  force: false
  interval: 5m
  path: ./flux/infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  suspend: true
  timeout: 2m