apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2025-10-07T23:36:31.5575234+02:00"
  creationTimestamp: "2025-10-07T21:32:12Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 4
  labels:
    kustomize.toolkit.fluxcd.io/name: apps
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: tandoor
  namespace: tandoor
  resourceVersion: "3402427"
  uid: ae1ace65-0403-4f93-a458-e6212a15dc27
spec:
  chart:
    spec:
      chart: tandoor
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gabe
        namespace: flux-system
      version: 0.9.9
  interval: 15m
  values:
    env:
      TZ: Europe/Berlin
    extraEnv:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          key: TANDOOR_SECRET_KEY
          name: tandoor-secret
    ingress:
      main:
        className: tailscale
        enabled: true
        hosts:
        - host: tandoor
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - tandoor
    persistence:
      config:
        accessMode: ReadWriteOnce
        enabled: true
        size: 5Gi
        storageClass: longhorn
      media:
        accessMode: ReadWriteOnce
        enabled: true
        size: 10Gi
        storageClass: longhorn-dual-disk
    postgresql:
      architecture: standalone
      auth:
        database: tandoor
        username: tandoor
      enabled: true
      image:
        registry: docker.io
        repository: bitnami/postgresql
        tag: 16.2.0-debian-11-r1
  valuesFrom:
  - kind: Secret
    name: tandoor-secret
    targetPath: postgresql.auth.password
    valuesKey: DB_PASSWORD
status:
  conditions:
  - lastTransitionTime: "2025-10-07T21:57:23Z"
    message: Failed to upgrade after 1 attempt(s)
    observedGeneration: 4
    reason: RetriesExceeded
    status: "True"
    type: Stalled
  - lastTransitionTime: "2025-10-07T21:57:23Z"
    message: 'Helm upgrade failed for release tandoor/tandoor with chart tandoor@0.9.9:
      context deadline exceeded'
    observedGeneration: 4
    reason: UpgradeFailed
    status: "False"
    type: Ready
  - lastTransitionTime: "2025-10-07T21:52:18Z"
    message: 'Helm upgrade failed for release tandoor/tandoor with chart tandoor@0.9.9:
      context deadline exceeded'
    observedGeneration: 4
    reason: UpgradeFailed
    status: "False"
    type: Released
  failures: 1
  helmChart: flux-system/tandoor-tandoor
  history:
  - appVersion: 1.5.31
    chartName: tandoor
    chartVersion: 0.9.9
    configDigest: sha256:7f281f0a88df59861c47e7153ee8d7dfad57d960263d8fba77ff86f06e039d85
    digest: sha256:f83dad0068a099d9743094dfe10e934557df458e3ecc31773272f521b4e6c01f
    firstDeployed: "2025-10-07T21:42:12Z"
    lastDeployed: "2025-10-07T21:52:22Z"
    name: tandoor
    namespace: tandoor
    status: failed
    version: 3
  - appVersion: 1.5.31
    chartName: tandoor
    chartVersion: 0.9.9
    configDigest: sha256:9220234c8e22b8e4497c05a581ea246014f8a6a2cd5546eeb4afb8de000f1a7f
    digest: sha256:f268b9d0d36dd152f6834005f6dab124ae50bc525515c575dfd8797c948b94c3
    firstDeployed: "2025-10-07T21:42:12Z"
    lastDeployed: "2025-10-07T21:47:17Z"
    name: tandoor
    namespace: tandoor
    status: failed
    version: 2
  - appVersion: 1.5.31
    chartName: tandoor
    chartVersion: 0.9.9
    configDigest: sha256:3ceeb4686343634651672ad985057fb3a7428fc39a8ee59bae1c44dbb83d1cf2
    digest: sha256:f3c8f664c8d44628f37064ef952ce7f4becfea6395bde0b6d071b6dc98ad4c5d
    firstDeployed: "2025-10-07T21:42:12Z"
    lastDeployed: "2025-10-07T21:42:12Z"
    name: tandoor
    namespace: tandoor
    status: failed
    version: 1
  lastAttemptedConfigDigest: sha256:7f281f0a88df59861c47e7153ee8d7dfad57d960263d8fba77ff86f06e039d85
  lastAttemptedGeneration: 4
  lastAttemptedReleaseAction: upgrade
  lastAttemptedReleaseActionDuration: 5m0.699504867s
  lastAttemptedRevision: 0.9.9
  lastHandledReconcileAt: "2025-10-07T23:36:31.5575234+02:00"
  observedGeneration: 4
  storageNamespace: tandoor
  upgradeFailures: 1
