apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-values
  namespace: minecraft
data:
  values.yaml: |
    minecraftServer:
      eula: true
      version: "1.21.10"
      type: "PAPER"
      memory: 8192M
      loadBalancerIP: 192.168.0.201
      
      pluginUrls:
        - https://cdn.modrinth.com/data/9eGKb6K1/versions/lbwRkfFH/voicechat-bukkit-2.5.28.jar
      
      serviceType: LoadBalancer
      
      extraPorts:
        - name: voicechat
          containerPort: 24454
          protocol: UDP
          service:
            enabled: true
            type: LoadBalancer
            port: 24454

      extraEnv:
          - name: RCON_PASSWORD
            valueFrom:
              secretKeyRef:
                name: minecraft-rcon-secret
                key: RCON_KEY
    
      rcon:
        enabled: true
        existingSecret: minecraft-rcon-secret
        secretKey: RCON_KEY
        
    persistence:
      dataDir:
        enabled: true
        Size: 20Gi
        storageClass: "longhorn-ssd-no-replica"
        
    resources:
      requests:
        memory: 8Gi
        cpu: 2000m
      limits:
        memory: 10Gi
        cpu: 4000m