apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: auth
data:
  configuration.yml: |
    theme: dark
    log:
      level: info
      format: text

    server:
      host: 0.0.0.0
      port: 9091

    authentication_backend:
      file:
        path: /config/users_database.yml
        password:
          algorithm: argon2id

    session:
      name: authelia_session
      secret: ${SESSION_SECRET}
      domain: pxldi.de
      same_site: lax
      expiration: 3600

    storage:
      local:
        path: /config/db.sqlite3
      encryption_key: ${STORAGE_ENCRYPTION_KEY}

    notifier:
      smtp:
        host: mail.pxldi.de
        port: 587
        username: "noreply@pxldi.de"
        password: "changeme"
        sender: "Authelia <noreply@pxldi.de>"

    access_control:
      default_policy: deny
      rules:
        - domain: "auth.pxldi.de"
          policy: bypass
        - domain: "traefik.pxldi.de"
          policy: two_factor
        - domain: "pihole.pxldi.de"
          policy: two_factor

    identity_providers:
      oidc:
        enabled: false

  users_database.yml: |
    users:
      admin:
        displayname: "Administrator"
        password: "$argon2id$v=19$m=65536,t=3,p=4$6pEKEARjMs7eDFk8VK+XQQ$rhZxAalU3uIreoUa/eCCByq/I/iFaeL/5cqLHWK+ae4"
        email: admin@pxldi.de
        groups:
          - admins