apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      chart: authelia
      version: 0.10.46
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system

  dependsOn: []
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
      hostname: auth.pxldi.de
      path: /
      tls: true

    service:
      type: ClusterIP

    persistence:
      enabled: true
      storageClass: longhorn
      size: 1G

    pod:
      annotations:
        checksum/config: "{{ .Files.Checksum \"config/configuration.yml\" }}"
      extraVolumes:
        - name: authelia-config
          configMap:
            name: authelia-config
      extraVolumeMounts:
        - name: authelia-config
          mountPath: /config
      envFrom:
        - secretRef:
            name: authelia-secrets

    envFromSecrets:
      - name: authelia-secrets