apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      chart: authelia
      version: 0.10.46
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system

  dependsOn: []
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    service:
      type: ClusterIP

    persistence:
      enabled: true
      storageClass: longhorn
      size: 1Gi

    configMap:
      session:
        cookies:
          domain: pxldi.de
          subdomain: auth
      storage:
        local:
          path: /config/db.sqlite3
      notifier:
        filesystem:
          filename: /config/notification.txt
      authentication_backend:
        file:
          path: /config/users_database.yml
      access_control:
        default_policy: deny
        rules:
          - domain: "auth.pxldi.de"
            policy: bypass
          - domain: "traefik.pxldi.de"
            policy: two_factor
          - domain: "pihole.pxldi.de"
            policy: two_factor

    pod:
      extraVolumes:
        - name: authelia-config
          configMap:
            name: authelia-config
      extraVolumeMounts:
        - name: authelia-config
          mountPath: /config