apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      chart: authelia
      version: 0.10.46
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system

  dependsOn: []
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    existingConfigMap: authelia-config
    service:
      type: ClusterIP

    persistence:
      enabled: true
      storageClass: longhorn
      size: 1Gi

    pod:
      extraVolumes:
        - name: authelia-config
          configMap:
            name: authelia-config
      extraVolumeMounts:
        - name: authelia-config
          mountPath: /config