apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      chart: authelia
      version: 0.10.46
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system

  dependsOn: []
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
      hosts:
        - host: auth.pxldi.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - auth.pxldi.de

    service:
      type: ClusterIP

    podAnnotations:
      configChecksum: "{{ .Files.Checksum 'config/configuration.yml' }}"

    persistence:
      enabled: true
      existingClaim: ""
      storageClass: longhorn
      size: 1Gi
      accessMode: ReadWriteOnce
      extraVolumes:
        - name: authelia-config
          configMap:
            name: authelia-config
      extraVolumeMounts:
        - name: authelia-config
          mountPath: /config

    envFromSecrets:
      - name: authelia-secrets