apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-server-config
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-server
  namespace: media-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre-server
  template:
    metadata:
      labels:
        app: calibre-server
    spec:
      containers:
      - name: calibre-server
        image: lscr.io/linuxserver/calibre:latest
        ports:
        - containerPort: 8081
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: "Europe/Berlin"
        - name: CLI_ARGS
          value: "calibre-server --port 8081 --userdb /config/users.sqlite --enable-local-write /books"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: books
          mountPath: /books
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: calibre-server-config
      - name: books
        persistentVolumeClaim:
          claimName: bookshelf-books
---
apiVersion: v1
kind: Service
metadata:
  name: calibre-server
  namespace: media-stack
spec:
  selector:
    app: calibre-server
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-opds
  namespace: media-stack
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.priority: "20"
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
spec:
  ingressClassName: traefik
  rules:
  - host: calibre.pxldi.de
    http:
      paths:
      - path: /opds
        pathType: Prefix
        backend:
          service:
            name: calibre-server
            port:
              number: 8081
  tls:
  - hosts:
    - calibre.pxldi.de
    secretName: calibre-tls