apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookshelf-downloads
  namespace: bookshelf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi