apiVersion: v1
kind: Secret
metadata:
    name: booklore-secrets
    namespace: booklore
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:OyBugi9fmE6fpDAOICLj9LsjCNY=,iv:/poce7GFa5IVZg4tWwpuniXyFirKevqH9M+de47sDNE=,tag:leq9jCY9I22oLEEEuc1Rtw==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:he2a/lXqhDOz5wrkC5AoaVbFCb0=,iv:taIli4mFBuSvuPxPHxvuNHmS9uto3+X8GsYQwQF7Z5U=,tag:WUP/V8Oaw+MpIZdrpBoQuQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:VyjPjFYq0J0Z2uxy8FZsXP0rhpw=,iv:514hgLK8AZ46oEc3/ErbqhMkAFwMjfyV6vzDoNYeODw=,tag:mNe524MFBxXCyUlfzdQ8GA==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxY0VJbm41N1MweTFOdlI5
            Q2JNcDF4NHZ5SHg2VUtwZFFMd3Q0MGtDZzBrCjBMOXNJSVhSeVd4bnM4Zi9vM1pW
            NUd1WHRuSitYSE5HZTh5RklXbVF1RmsKLS0tIEZWMklmZW1vb0FHUm1TYTFnYVYw
            NFMwYk9FMnAxMUdzZm00UGcyQ2d2bWsK6gQvbN0huRttlzkxLAfu2gQuRjbLoroa
            nMlNtNQqKXAElPeo+P06X6B3wKi5n+LmvcCoS8zeoa9vDpIXmUS5Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T23:18:42Z"
    mac: ENC[AES256_GCM,data:mljlegNsr2CRqlfa4i4GYzpVNCQXaUynbMl5m+6PLnfn1dus6k3p7L8YL9fJb4Ttue0InWek+aj8rzPY8gcw4//xyBDMXaqlINJMRMcRoq06RUdjZFJHKQ06KJ91UFAJNXEY1S/H9r5YqBeG/sdoxJobWdMQqfwyeg82Qeb0PwY=,iv:mev/dUwJnAhPyvBEjoDgcMxqkrUpKy4VQxBPzc7vTb8=,tag:9ceMQYr+ogV3GjUHDPYrbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
