apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: jellyfin
      version: "21.8.0"
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system

  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
      path: /
      pathType: Prefix
      hosts:
        - jellyfin.pxldi.de
      tls:
        - hosts:
            - jellyfin.pxldi.de
          secretName: jellyfin-tls-secret

    jellyfin:
      env:
        TZ: Europe/Berlin
      resources:
        limits:
          cpu: 4000m
          memory: 4Gi

    persistence:
      media:
        enabled: true
        existingClaim: media-pvc
        mountPath: /media
      config:
        enabled: true
        storageClass: longhorn
        size: 10Gi
      cache:
        enabled: true
        storageClass: longhorn
        size: 5Gi