apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: jellyfin
      version: "22.2.26"
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system

  values:
    ingress:
      main:
        enabled: true
        primary: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
        hosts:
          - host: jellyfin.pxldi.de
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - jellyfin.pxldi.de

    jellyfin:
      env:
        TZ: Europe/Berlin
      resources:
        limits:
          cpu: 4000m
          memory: 4Gi

    persistence:
      media:
        enabled: true
        existingClaim: media-pvc
        mountPath: /media
      data:
        enabled: true
        size: 100Gi
        storageClass: longhorn
      config:
        enabled: true
        size: 10Gi
        storageClass: longhorn-dual-disk
      cache:
        enabled: true
        size: 10Gi
        storageClass: longhorn-single-replica