apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media-stack
spec:
  interval: 12h
  chart:
    spec:
      chart: radarr
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      version: ">=20.0.0"
  values:
    metrics:
      main:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: tailscale
        hosts:
          - host: radarr
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - radarr
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 5Gi
      media:
        enabled: true
        existingClaim: media-pvc
        mountPath: /media
      downloads:
        enabled: true
        existingClaim: downloads-pvc
        mountPath: /downloads