apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media-stack
spec:
  interval: 12h
  chart:
    spec:
      chart: radarr
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      version: ">=20.0.0"
  values:
    metrics:
      main:
        enabled: false
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia-forwardauth@kubernetescrd
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
        hosts:
          - host: radarr.pxldi.de
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - radarr.pxldi.de
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 5Gi
      media:
        enabled: true
        existingClaim: media-pvc
        mountPath: /media
      downloads:
        enabled: true
        existingClaim: downloads-pvc
        mountPath: /downloads