apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media-stack
spec:
  interval: 12h
  chart:
    spec:
      chart: sabnzbd
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      version: ">=18.0.0"
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: tailscale
        hosts:
          - host: sabnzbd
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - sabnzbd
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 5Gi
      downloads:
        enabled: true
        existingClaim: downloads-pvc
        mountPath: /downloads