---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-config
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-dual-disk
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-downloads
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slskd
  namespace: media-stack
  labels:
    app: slskd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: slskd
  template:
    metadata:
      labels:
        app: slskd
    spec:
      containers:
      # Gluetun VPN sidecar
      - name: gluetun
        image: qmcgaw/gluetun:latest
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        env:
        - name: VPN_SERVICE_PROVIDER
          value: "custom"
        - name: VPN_TYPE
          value: "wireguard"
        - name: FIREWALL_INPUT_PORTS
          value: "5030"
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "192.168.0.0/16,10.0.0.0/8"
        - name: TZ
          value: "Europe/Berlin"
        ports:
        - containerPort: 8888
          name: http-proxy
        volumeMounts:
        - name: wireguard-config
          mountPath: /gluetun/wireguard
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      
      # Slskd main container
      - name: slskd
        image: slskd/slskd:latest
        env:
        - name: SLSKD_HTTP_PORT
          value: "5030"
        - name: SLSKD_HTTPS_PORT
          value: "5031"
        - name: SLSKD_SLSK_LISTEN_PORT
          value: "50300"
        - name: SLSKD_NO_AUTH
          value: "true"
        - name: SLSKD_SLSK_USERNAME
          valueFrom:
            secretKeyRef:
              name: slskd-soulseek-creds
              key: SLSKD_SLSK_USERNAME
        - name: SLSKD_SLSK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: slskd-soulseek-creds
              key: SLSKD_SLSK_PASSWORD
        - name: SLSKD_REMOTE_CONFIGURATION
          value: "false"
        volumeMounts:
        - name: config
          mountPath: /app
        - name: downloads
          mountPath: /var/slskd/downloads
        - name: music
          mountPath: /music
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
      
      volumes:
      - name: wireguard-config
        secret:
          secretName: slskd-wireguard-config
      - name: config
        persistentVolumeClaim:
          claimName: slskd-config
      - name: downloads
        persistentVolumeClaim:
          claimName: slskd-downloads
      - name: music
        persistentVolumeClaim:
          claimName: music-library
      
      shareProcessNamespace: true
---
apiVersion: v1
kind: Service
metadata:
  name: slskd
  namespace: media-stack
spec:
  selector:
    app: slskd
  ports:
  - name: http
    port: 5030
    targetPort: 5030
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slskd
  namespace: media-stack
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia-forwardauth@kubernetescrd
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
spec:
  ingressClassName: traefik
  rules:
  - host: slskd.pxldi.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: slskd
            port:
              number: 5030