apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonobarr-config
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonobarr
  namespace: media-stack
  labels:
    app: sonobarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonobarr
  template:
    metadata:
      labels:
        app: sonobarr
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: sonobarr
        image: ghcr.io/dodelidoo-labs/sonobarr:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: secret_key
          valueFrom:
            secretKeyRef:
              name: sonobarr-secrets
              key: secret_key

        - name: last_fm_api_key
          valueFrom:
            secretKeyRef:
              name: sonobarr-secrets
              key: last_fm_api_key
        - name: last_fm_api_secret
          valueFrom:
            secretKeyRef:
              name: sonobarr-secrets
              key: last_fm_api_secret
        
        - name: lidarr_address
          value: "http://lidarr.media-stack.svc.cluster.local:8686"
        - name: lidarr_api_key
          valueFrom:
            secretKeyRef:
              name: sonobarr-secrets
              key: lidarr_api_key
        - name: root_folder_path
          value: "/music/"
        - name: quality_profile_id
          value: "1"
        - name: metadata_profile_id
          value: "1"

        - name: sonobarr_superadmin_username
          value: "admin"
        - name: sonobarr_superadmin_password
          valueFrom:
            secretKeyRef:
              name: sonobarr-secrets
              key: sonobarr_superadmin_password
        - name: sonobarr_superadmin_display_name
          value: "Poldi"
        volumeMounts:
        - name: config
          mountPath: /sonobarr/config
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sonobarr-config
---
apiVersion: v1
kind: Service
metadata:
  name: sonobarr
  namespace: media-stack
spec:
  selector:
    app: sonobarr
  ports:
  - name: http
    port: 5000
    targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonobarr
  namespace: media-stack
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia-forwardauth@kubernetescrd
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
spec:
  ingressClassName: traefik
  rules:
  - host: sonobarr.pxldi.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonobarr
            port:
              number: 5000
  tls:
  - hosts:
    - sonobarr.pxldi.de