apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server-data
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd-no-replica
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      containers:
      - name: matter-server
        image: ghcr.io/home-assistant-libs/python-matter-server:stable
        ports:
        - containerPort: 5580
          name: websocket
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: MATTER_SERVER_STORAGE_PATH
          value: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: matter-server-data
---
apiVersion: v1
kind: Service
metadata:
  name: matter-server
  namespace: home-assistant
spec:
  type: ClusterIP
  selector:
    app: matter-server
  ports:
  - port: 5580
    targetPort: 5580
    name: websocket