apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor
  namespace: tandoor
spec:
  interval: 15m
  chart:
    spec:
      chart: tandoor
      version: "0.9.9"
      sourceRef:
        kind: HelmRepository
        name: gabe
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: tandoor-secret
      valuesKey: DB_PASSWORD
      targetPath: postgresql.auth.password
  values:
    env:
      TZ: "Europe/Berlin"

    ingress:
      main:
        enabled: true
        className: tailscale
        hosts:
          - host: tandoor
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - tandoor

    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 5Gi
        accessMode: ReadWriteOnce
      media:
        enabled: true
        storageClass: longhorn-dual-disk
        size: 10Gi
        accessMode: ReadWriteOnce

    postgresql:
      enabled: true
      architecture: standalone
      image:
        registry: docker.io
        repository: bitnami/postgresql
        tag: 16.2.0-debian-11-r1
      auth:
        database: tandoor
        username: tandoor