apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor
  namespace: tandoor
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  dependsOn:
    - name: tandoor-postgresql
      namespace: tandoor
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/tandoorrecipes/recipes
              tag: 2.3.6

            env:
              TZ: "Europe/Berlin"
              ALLOWED_HOSTS: "recipes.pxldi.de,tandoor.tandoor,tandoor,localhost"
              SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: tandoor-secret
                    key: TANDOOR_SECRET_KEY
              ENABLE_SIGNUP: "0"
              ENABLE_PDF_EXPORT: "1"

              DB_ENGINE: "django.db.backends.postgresql"
              POSTGRES_HOST: "tandoor-postgresql-primary.tandoor.svc.cluster.local"
              POSTGRES_PORT: "5432"
              POSTGRES_DB: "tandoor"
              POSTGRES_USER: "tandoor"
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: tandoor-secret
                    key: DB_PASSWORD

              SUPERUSER_NAME: "admin"
              SUPERUSER_EMAIL: "xd@pxldi.de"
              SUPERUSER_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: tandoor-secret
                    key: DB_PASSWORD

            probes:
              liveness:
                enabled: true
                spec:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 6
              readiness:
                enabled: true
                spec:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 3
              startup:
                enabled: true
                spec:
                  httpGet:
                    path: /
                    port: 80
                  failureThreshold: 60
                  periodSeconds: 5

    resources:
      main:
        containers:
          main:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "250m"

    service:
      main:
        controller: main
        ports:
          http:
            port: 80
            protocol: TCP

    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
        hosts:
          - host: recipes.pxldi.de
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - recipes.pxldi.de

    persistence:
      mediafiles:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: longhorn-dual-disk
        globalMounts:
          - path: /opt/recipes/mediafiles

    staticfiles:
      enabled: true
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      size: 2Gi
      storageClass: longhorn
      globalMounts:
        - path: /opt/recipes/staticfiles