apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor
  namespace: tandoor
spec:
  interval: 15m
  chart:
    spec:
      chart: .
      version: "1.5.31"
      sourceRef:
        kind: HelmRepository
        name: tandoor-chart
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: immich-jwt
      valuesKey: DB_PASSWORD
      targetPath: postgresql.auth.password
  values:
    env:
      TZ: "Europe/Berlin"

    ingress:
      main:
        enabled: true
        className: tailscale
        hosts:
          - host: tandoor
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - tandoor

    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 5Gi
      media:
        enabled: true
        storageClass: longhorn-dual-disk
        size: 10Gi

    postgresql:
      enabled: true
      architecture: standalone
      auth:
        database: tandoor
        username: tandoor