apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor-postgres
  namespace: tandoor
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 18.0.8
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: tandoor
      password: tandoorpass
      database: tandoor
    primary:
      persistence:
        enabled: true
        size: 2Gi
        storageClass: longhorn