apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    persistence:
      defaultClass: true
      reclaimPolicy: Delete
    defaultSettings:
      defaultReplicaCount: "2"
      replicaSoftAntiAffinity: "true"
      replicaAutoBalance: "best-effort"
      defaultDataPath: /var/mnt/hdd1
      guaranteedEngineManagerCPU: "0"
      guaranteedReplicaManagerCPU: "0"
    ingress:
      enabled: true
      ingressClassName: tailscale
      host: longhorn
      tls:
          - hosts:
            - jellyfin