apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-dual-disk
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"