apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 15m
  chart:
    spec:
      chart: pihole
      version: 2.x.x
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  values:
    serviceWeb:
      type: ClusterIP
      httpPort: 80
    serviceDns:
      type: LoadBalancer
      externalTrafficPolicy: Local
    persistentVolumeClaim:
      enabled: true
      size: 2Gi
      storageClass: longhorn

    admin:
      enabled: false

    DNS1: "1.1.1.1"
    DNS2: "8.8.8.8"

    ingress:
      enabled: true
      ingressClassName: tailscale
      hosts:
        - host: pihole
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
          - pihole