apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 15m
  chart:
    spec:
      chart: pihole
      version: "2.34.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system

  values:
    DNSMASQ_LISTENING: all

    serviceDns:
      enabled: true
      mixedService: true
      type: NodePort
      port: 53
      nodePort: 3053
      externalTrafficPolicy: Local

    serviceWeb:
      type: ClusterIP
      http:
        enabled: true
        port: 80
      https:
        enabled: true
        port: 443

    persistentVolumeClaim:
      enabled: true
      size: 2Gi
      storageClass: longhorn

    admin:
      enabled: false

    DNS1: "1.1.1.1"
    DNS2: "8.8.8.8"

    ingress:
      enabled: true
      ingressClassName: tailscale
      annotations: {}
      path: /
      pathType: Prefix
      hosts:
        - pihole
      tls:
        - hosts:
            - pihole

    persistentVolumeClaim:
      enabled: true
      size: 2Gi
      storageClass: longhorn