apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 15m
  chart:
    spec:
      chart: pihole
      version: 2.x.x
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  values:
    DNSMASQ_LISTENING: all
    serviceWeb:
      type: ClusterIP
      httpPort: 80
    serviceDns:
      enabled: true
      mixedService: true
      type: ClusterIP
      annotations:
        tailscale.com/proxy-group: ingress
        tailscale.com/hostname: pihole
    persistentVolumeClaim:
      enabled: true
      size: 2Gi
      storageClass: longhorn

    admin:
      enabled: false

    DNS1: "1.1.1.1"
    DNS2: "8.8.8.8"

    ingress:
      enabled: true
      ingressClassName: tailscale
      annotations: {}
      path: /
      pathType: Prefix
      hosts:
        - pihole
      tls:
        - hosts:
            - pihole