apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
  namespace: searxng
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      searxng:
        annotations:
          secret.reloader.stakater.com/reload: searxng-secret
        strategy: RollingUpdate
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 1000
            runAsUser: 1000
            runAsNonRoot: true
        initContainers:
          fix-permissions:
            image:
              repository: alpine
              tag: latest
            command:
              - sh
              - -c
              - |
                cp /tmp/config/settings.yml /etc/searxng/settings.yml
                cp /tmp/config/limiter.toml /etc/searxng/limiter.toml
                chown -R 1000:1000 /etc/searxng
            securityContext:
              runAsUser: 0
        containers:
          app:
            image:
              repository: ghcr.io/searxng/searxng
              tag: latest
            env:
              SEARXNG_BASE_URL: "https://search.pxldi.de"
              SEARXNG_URL: "https://search.pxldi.de"
              SEARXNG_PORT: &port 8080
              UWSGI_WORKERS: 2
              UWSGI_THREADS: 4
              INSTANCE_NAME: "SearXNG"
            envFrom:
              - secretRef:
                  name: searxng-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: false
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi

    service:
      app:
        controller: searxng
        ports:
          http:
            port: *port

    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.middlewares: |
            auth-traefik-authelia-forwardauth@kubernetescrd,
            searxng-searxng-headers@kubernetescrd
          traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
        hosts:
          - host: search.pxldi.de
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - search.pxldi.de

    persistence:
      config-source:
        type: configMap
        name: searxng-config
        advancedMounts:
          searxng:
            fix-permissions:
              - path: /tmp/config
      config:
        type: emptyDir
        globalMounts:
          - path: /etc/searxng
      tmpfs:
        type: emptyDir
        advancedMounts:
          searxng:
            app:
              - path: /tmp
                subPath: tmp