apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
    namespace: homepage
type: Opaque
stringData:
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:jNr4cu6/1f/DvJqtRSStCtV9/FJ87ms1qFNV3kEUi4Y=,iv:B9RKKt+cX3D9+zQSI1ISjwD0agwhwlugjTzu1quN75A=,tag:GGT3Rg0IR9HotTMJDp3AXQ==,type:str]
    IMMICH_API_KEY: ENC[AES256_GCM,data:xKYXDevwgz4aReTpEdxHl4kCdG15B7it/RHi6emZ46AI+KhM3UT3OA==,iv:7rhI1Y1Yii8LsbeeITjdNnoplB5evz4Q6plHzuew9RY=,tag:fxaYPlkQsx36UX+Fo74eig==,type:str]
    PIHOLE_API_KEY: ENC[AES256_GCM,data:papO0g+ms86Wtl6T318GahkPn+DVzTvHOELSt9/2AMTKUYvSBkV84cbO5Bc=,iv:bsaQMRlhLUvdQgZYtW2SBiYUxTmR9kGF2h/VpIUturU=,tag:iSidofS/O1m34sTWpTEhvQ==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:DbMTWiShaUtFS0uhEZRD4ftuS830KAWfUMx+WJvN0/E=,iv:0E8CgQhF5RPpfjuXZbh4aLnQyGpY1m6auK/CtwfO8XM=,tag:HmQHBo/KfTyCAHykHn+WTQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:pyl1tdGckRvJW13lLVnQ94deRsQwygj7gJJH4jMdw4o=,iv:ezMBf3XRU9pcPRZvjzqpZra+tAMQx4JVhGAp5/4I4jw=,tag:7rQUgdIyjMUPAe8TCjfxNw==,type:str]
    SABNZBD_API_KEY: ENC[AES256_GCM,data:u/ZHYShEQOAyOMXh8iKmm5p+oBp365Lzkgoz8RQu4T8=,iv:BtTwLeDsO9QoBY3uDFiGeFk5F4AepXtd0kASmhREA4A=,tag:fptnVqQFEnXn0fr0uN5YSg==,type:str]
    TANDOOR_API_KEY: ENC[AES256_GCM,data:iF61T0U23rxd74hsB/7JVwbVOyKBk6PWeTvpfNgmMMGOWo5YFxVd2Q==,iv:riRjN+/6p2XSRLP1AySwamzgoflgEgU5KBqRhH4z494=,tag:hjsCOMOdjGlHzYmyWyR8BA==,type:str]
    NEXTCLOUD_API_KEY: ENC[AES256_GCM,data:wI1abzm6al0BeCREKoEatYLpJqLBz1Yx3Uog3GJYIqI=,iv:mxoKd0sDXS0rmeiLy1OHo9D7fW+tpkxEbKT+LuwF/oI=,tag:lKzMnV4lrhTXdvqBepkQIw==,type:str]
    CMC_API_KEY: ENC[AES256_GCM,data:FoeFigxQYMdoI8W3F232Vbmve43UfrT9z4b0/3YZrhk=,iv:s9GQpq833XEeEt4BVnfZQhOaORL1+fmlOFZ/he8QIqU=,tag:yyNCffkBAo+IECzjdXnlxg==,type:str]
    FH_API_KEY: ENC[AES256_GCM,data:uCE4wE6MCQYy+92Jm7jn0USVQz6+mOTP3K34QU4+raLEskgO5mwQGg==,iv:RhqLXTT/dMsqjqD5qlCcjhS0cZxtiPFUmixvXcyz+7c=,tag:IgxynbtvT7HpSrtPbJdh1Q==,type:str]
    CITY_NAME: ENC[AES256_GCM,data:N2YZ6M61i0k=,iv:XPQyhaN0uqUqiRlEtv+idJrJHQ9upyflay0D3av2zkU=,tag:dcYJi76E9BXEK5B0+GsBXQ==,type:str]
    CITY_LATITUDE: ENC[AES256_GCM,data:swUPKs8kXlxJ,iv:3q4AQgrxud+SEIEukiZ/bhgr6vQzKJtN0iRgnMRztrU=,tag:knnQTBecrP5LkJAzd91FyQ==,type:str]
    CITY_LONGITUDE: ENC[AES256_GCM,data:dM5RKrrgMA==,iv:z6jPXyz6obar/tP522pD2do2DmV6tdxh5YBmlE5sGh0=,tag:UAJ25akVX+f5MbovwxMLDA==,type:str]
    GRAFANA_USER: ENC[AES256_GCM,data:ApTfaaQ=,iv:ojN6YampN2vnBUn8ZRUSRBMTt1lL46TlHFwMZVcZLWo=,tag:9r7VGuX/3g8CaQpWE5iTHg==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:NFoTkRIcfTKhknumdRH36XePdzo=,iv:/LNEdwvMBe0EKaufqop6V6QxrW6IBb4oduZlVI2XcWM=,tag:+mKf6pEzz5/RkKEqeAZZ2g==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsekc1SlRXRm1uYW1tWC84
            K2Y5THEvbkdoRDVrMmRPQmdTY3ZRT00vbTFNCmF4QVQ4RUs1L0xwV0ZITGU1V1FT
            ZGNqenhwUHZGUUl0bnZvNG9DYnozS00KLS0tIEVtWkxKSFBmeFh0dWdnRFIrM0Qw
            aTJ5bFFLbExrZ0NRSXEyQUJXZ1lSQ2sKgZmio8v6AhyYVRFeRCGoMKUeJ875hFtn
            6s1vmcudYBMFO8Xp0Gbg3h2AAOy4+oNI3rAQacoMxD5B227fB4mIjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T13:40:39Z"
    mac: ENC[AES256_GCM,data:xu4wKyxpIaBcqgcZpvmLdJwLQOcfJtHPK88cSvLqU/vUQG9XhGmB0exmUlSgz8Z0Bei1JplSaWLo3Pj9TWfDBQ/bvGsyTRpriijhI/3mgUz/PW/uYWYiHBaHVXeWYjuAdpHaiTS4ZkaqoU4NqX8dsLbzy29PB9SjqTDMIQOfHnA=,iv:j6wlmNZeHc/4F4Jm4tnIY6z0TqJH/5CBbXi/IZ0NIx8=,tag:v5GT6OrC8XRNGGJHNn4CiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
