apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
    namespace: homepage
type: Opaque
stringData:
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:1HJbaG6EyQiRoFAeKNoJymyctdnd8Lu7056tvUlvvrA=,iv:hnGcqXXxAoIuGKXTg47RuojTYjWunXDAkGJOwC97hgY=,tag:cx2uO7p+AwM0Yfusm0Z1Zw==,type:str]
    IMMICH_API_KEY: ENC[AES256_GCM,data:F92gQUn3XHQotKjg56onBL1MpySyWmpixqgH1wkz5/l60FtVt4iF/Q==,iv:Gldsce8lSocn08zc/rhfYyJhGvuGh2mBKrQCqeRTBs4=,tag:gPXxGo8V5AToYEb3fV6xjQ==,type:str]
    PIHOLE_API_KEY: ENC[AES256_GCM,data:ilZSscdpJnAXJkFrSr9MSzCdL9F8UJnPFTvBOLxm5GLVr4IkyT57q5o41rE=,iv:oZz6LvV2Jh+vGnixscCNxOqel6HBj58Dpp2mjaxgNdM=,tag:DM0Vt2xjdfRVcipCqmsB8Q==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:Rf2iX2wcvp+LWmUotua1WpkNh4ebnJvoTTYkdeGjlOE=,iv:oCB5+ZeOMUOMAIdYSRFNpXcqIZOBqJOE3OLaJ97PxLE=,tag:xJ9QVPhl4lgbx7tdIylXjQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:cyVcOW24hR65Q/hKpuzd6Zj7P4y6tTRFPF7/TGUHGw8=,iv:r8ta9Efi5tMrbmDgY+i6f1PAeQtTC73LUrRGFQbvmWI=,tag:Nlz8QRCwqus9d+8fcvDXww==,type:str]
    SABNZBD_API_KEY: ENC[AES256_GCM,data:Fs/3rjpSV4rpESf7XGyLMdUpaB0kK+A2c+aqTQ0jVRw=,iv:1SklXH+57z37kM/5ZpXPCeYbf8AH2M2RAK0uWOWm5MQ=,tag:xCeBbcyZ09FWPnKRqlAR5g==,type:str]
    TANDOOR_API_KEY: ENC[AES256_GCM,data:r4UGiHHuN8Iazpmzt9s6fWfeWFUx3DfzL8N0a5dFjF63DYZTtRyjnQ==,iv:hHbVWBO7grqLxw0hNxvjINyfxCGKrki26FOAP2w35jw=,tag:We1yja3GhbJaUqN/02sblg==,type:str]
    NEXTCLOUD_API_KEY: ENC[AES256_GCM,data:DqxsHo/XsWwjGrSo2rG5+Fz6LUTqaRlnNyowyoS9g08=,iv:2lR9b6Cx/JYq3MafHoYG5eX9X+IijXWmAdEvqGIqack=,tag:Ws00XaaO9ypfHZNiAnm4Kw==,type:str]
    CITY_NAME: ENC[AES256_GCM,data:6Y2I40j0oDc=,iv:sg2086i/lGDdJXymvVAFuv6+/8DNIcjyVsw2zWzv5oU=,tag:q7p5nO3KyF1X+5rx8Xf3mA==,type:str]
    CITY_LATITUDE: ENC[AES256_GCM,data:I2tryd95ShLC,iv:VBoHxlQfRN96gsrRZ+IJmu4O8h7Y4jt3Ays2zCb7Gdw=,tag:0b9h5gVWqgDF4CW1+bHmaQ==,type:str]
    CITY_LONGITUDE: ENC[AES256_GCM,data:Oou4rZ0q0w==,iv:WD92wJG/FAfFUmxKX4Mb79sLqo8FzbjN3OOSrL1SBvE=,tag:HUiFMv2yJPRsFVT9mbif2g==,type:str]
    GRAFANA_USER: ENC[AES256_GCM,data:npZNybE=,iv:1PlSYCpzDrv6LC2D3GQ4+M++FHRzJngftJJuiI4jrhw=,tag:Mp0KA1Fc90Wyc1uhGSU7IQ==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:J32qRrqSXwu2W9vzQ71tKXFI/mg=,iv:kEC+apx2MAkfFq1i/XHL6drx/MugNQXyFOmGY/stkpk=,tag:SS4GLkuH5Z2iUM4hXjdbfw==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbkpwU0pKM0pRYm80RUpa
            alVmQXBvZlBMbWNoYkJaNnNUYURUWHNUaTJVCkMySCtJWjdqMklHT3RoZzZVUjBi
            Zko2czlIR3dlTmdYU0NUUnlrVnB0b0UKLS0tIGJQNk5namxkK0lScktLZFRvQ2ox
            SGtaTVZ0UFZ3RXc4ZW56bU12NTVWbjAKepg6eD6q/s9fHXFCxVmFxvt/yd5qw4XU
            Pb9sYBj9dS3tWTRCi/CFB3Yrddkjs9+KB5q5EICyT53rkd4L8iUQFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-28T01:21:41Z"
    mac: ENC[AES256_GCM,data:xHXES+4Ysu998mo4AM+xvInXCw9qpfu7s/Ox3ikfCNE0bEI8ruFSIOvIyljyMe4EXuqtgocyYTtRXyYydsUi0hnys53CcdixCiCXzvhruk3OnBhSU5nCAPOC3Cv2naE6IsX4psM78+SjxDdL6sHOS4EWRSjoBRfOfmy+WbzntJI=,iv:fo2lZ3HfAPszHE7I8S9TUapzPqgffL/0lZn2HW9YfzU=,tag:kOrUpX/LVlNCj5pTnIhWEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
