apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
    namespace: homepage
type: Opaque
stringData:
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:WIFGMkc8Wf+xIZzu7s0MDCa+iFb0WzVCX5+t1O9wu50=,iv:GgiThjGh2tq2SPwEpPNcTfotVYEtgrCWvbNHCdYB5ME=,tag:0BHdx2UbXsEPhiWv53Z/wQ==,type:str]
    IMMICH_API_KEY: ENC[AES256_GCM,data:XsfuCfU+gjXxxzy9kigQreYjzAZLi89nSnO3DzgcKbQ2BK/FivH5og==,iv:ejXp0Vlls3IYTinlb4DHowyyVLNQriSXfRZSiXcQzpg=,tag:tcjOexmJbYE4+UAtqEE9AQ==,type:str]
    PIHOLE_API_KEY: ENC[AES256_GCM,data:8q3+UF+pb2AwlexWIqM5Lr/MqL7mHloE/NE5Pppv39V9KMNNKwVbF2B4uPI=,iv:CyywSDsjGK/Lt7Nb86iIpf/klQr9bu693zrbjNWJkSo=,tag:VgjjvY9EBv0s5KGaI0k3GQ==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:hzxE9gRHuIP7mZUKfUsFuuES3bSn2DkTW5lC4MERVMw=,iv:lEjajz2+enfmqZEonYNbFwJqjqvdIJz/fj0DJ3T8oeU=,tag:8GbxCFQKJF1hSrNnw0HeFQ==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:Ap4IE6+VJC2f42JvS0NuZFvRFGiCKfAu3eRw7kohSwY=,iv:ENjXmazJGVuhzIxItajFmgfYZsT7t5Bo4fnIBTCKhDQ=,tag:2HATrvJpHQsf3Y0wfVrvhw==,type:str]
    SABNZBD_API_KEY: ENC[AES256_GCM,data:8lQFfU4mjkl2ruwBpaAM7L/ctd1/uITnrb98/tkqMvw=,iv:JOmZl182lA1fpA5EgiL0R00jxUOm8m1cG03NYy3c0Pw=,tag:ib0ddJZoE86pWodxGw4PAQ==,type:str]
    CITY_NAME: ENC[AES256_GCM,data:df6gOMiTJlo=,iv:9NUpLimaHO/VJ7lsVbwm5z4ToOJ0nsD7IfXSOLElMlQ=,tag:3P9vY7CV3PZwO6ii3m4uRQ==,type:str]
    CITY_LATITUDE: ENC[AES256_GCM,data:7yCoJ4dLH6Hp,iv:94btZxPF+jx+OaK2rCu+43VELREPl7oEmOmpy/G1E14=,tag:q4QieOik8eHs5wqXk/bOUg==,type:float]
    CITY_LONGITUDE: ENC[AES256_GCM,data:fIcJKMk15w==,iv:ak8/x3u2mCjKGj3LKFGuhihMV+3D/9Xx7CgkSLZJhQQ=,tag:1wmt2FulW4LgkT3xNAPSug==,type:float]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaVZmL0ladmc0MWl1cm1z
            bWNyVG83TUc5SDZZdEVxcDl3V1lXbktVOTJrCk5zK2ZMMWxJYlBTS2tsNlJkQXBF
            Y1ltZk92SjlyQ3VHdmlCbUZEeG1vNGMKLS0tIDU4QzNWaEcwMlIvV05OUUJNbzEw
            ODRmYnlGZW95ZUpndWliOWxjVXdDTXMKWZC6/H0YGGsy2LIz0vuOIk6O0208b+0y
            YsavBoOvq8KJ6un5QbDqO+A4uWcV4+DPE41x+cI3+nBZ00FaQGSnpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T12:10:38Z"
    mac: ENC[AES256_GCM,data:THigMMsYPaePyZ5xbdhBsEr3ua2ZdZwSb2CTHqLg1Xuy1fwP8Rm0b0hwC19qYSbh9VyPgKb2OoB+UC6WLQNU6z62AwN2iYdhKicbU/43Rchu4Cu6YBOSNtLeDo7ueqE7bM+hjO0a5anR7lE5VJfxoFR4AG5AOd7SzEy5w8wDyh8=,iv:YGmz1Ks9ZhwOq2lvbG1xwZGdQYe0JzAFnCI2GjCJiZU=,tag:DievuEwZZxHIcmvwP4bojw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
