apiVersion: v1
kind: Secret
metadata:
    name: homepage-secret
    namespace: homepage
type: Opaque
stringData:
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:/qXcvjuN1WI7+nj5FXGKPS+XYyz/4KjwhbS/buJ0Ymo=,iv:sgsQclLqBTwIaDBYzo3USG6t5UQ6fTPlYyz+NMZXYfI=,tag:o4jux9pCbv/4X1wpBk1HQg==,type:str]
    IMMICH_API_KEY: ENC[AES256_GCM,data:TpE8w9zF4gz61092f3XDgP84VTdako7GtrBLcJONTezrfe5V/ljNaQ==,iv:2cLxsG5OKM1Yd4ZTU6uEFBiYhpZ1aEAO0zty7Iezcw8=,tag:343SLbzC1cXt35DbUINXCg==,type:str]
    PIHOLE_API_KEY: ENC[AES256_GCM,data:sB7CtVyrLSTDoP065L8YHLtTCxfRx34n8pS8YGa8RimZ4Gegm7JEMCsdEEc=,iv:eL0xKP8unUyAX4FcDKa+LE+p6a2EErBD32B9VBHM5Vg=,tag:syp6aPBfsRZ5PK76XQsOAQ==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:PoRkvAl9w2emouVaOgWCjgyIPb0vY0J1svURxmCXpPM=,iv:J/G/jziRFaBDB68xnGR109CN075RlTvxCSLAfJYzFdU=,tag:HQuniAAzaB/qHobRhcud7w==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:Oc+s0jGVvj+thag/qhKCuWaZsL6+hhOqzdnn+g4Tt8E=,iv:ew+DQ7iiF5SjnAvUZJDyA8nk1TtH3RzM2vRzvJnQ8rY=,tag:WA9sKceGiVCJ/wwjvcrLJA==,type:str]
    SABNZBD_API_KEY: ENC[AES256_GCM,data:5TLyMoyn8m1vgSAXAdNto3a4g9tNerOetDpBT1Iz6C4=,iv:jg9tHnO5BdbSRU1sD+N0+cfxY7goY8eD7J4T3Rs6Vvk=,tag:Ntq2kRPk+cjurVTNWXW4Jw==,type:str]
    CITY_NAME: ENC[AES256_GCM,data:e8/yngdszS4=,iv:1tP5QYeK2ffmPr0If00Q+gM1U6FrwE8YuEv0oUT34R4=,tag:NyxegPvQr43EbH7oMOtdeg==,type:str]
    CITY_LATITUDE: ENC[AES256_GCM,data:pZXe2WBpojOT,iv:c2oPA3DX49R1cu5zT4lpmpzxDy4kqN6+i9LcbO7jhmo=,tag:Q+0oBCT0XdZeeb1gefAwtg==,type:str]
    CITY_LONGITUDE: ENC[AES256_GCM,data:dE94Jna1Lw==,iv:NL1XjzoMk1q6QBcj+a0ECtL95o7qCOcWAapH7VlSWk0=,tag:UdIwQfw9YJL/dqMATjarlA==,type:str]
    GRAFANA_USER: ENC[AES256_GCM,data:TAA6hUM=,iv:lE4ReMe9wgRga7sycHpnXLeFUaAuODRudfqHLxtvio8=,tag:SItGRYod9TezdFRkcUYWMw==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:uCifXRHcl9oVC9xFPZBfAlbZm+g=,iv:kuyTYjEwLL9CJhvEaeP8s4+Xg4ulEK3m9T/kJL4fb/M=,tag:woi3T33vo43VExI4HaH1qw==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaEJrSUFoSnE5aEdIQ2VX
            V09KRjlvM1ZTUzRqcEVXQkd6VFIzOXdpTTJBCjU2QXJSc2J3UnNQR0pGY1FTTWNE
            VGE0ZzV3RXZWWVprUkcvTDYxc3d2SjQKLS0tIHVpQmZwMGxHM1FYSytaZ0k4U2ly
            UVp3UFN1dDJMQzZBM0hEMmEvOXdwK0EKy3HVNMFGpKwB0FzsF/t/81hQ1/hu9zjN
            TBKHOUoHVrsvVsDTeHJE8/wAQZ3MhOpdEJPXmwOyPoM4k4pzjvPOEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T19:00:06Z"
    mac: ENC[AES256_GCM,data:gaj4n882+kOJhmkCbUNR9astZ1zDOKpP8S4Mzw8JvjIJKf9kZW6li14Vr/UU64MNFmPAorhR0JxYk2g2rft2V7O0xJjlmcrKwBmRtgSlHMB3vTQxqYbg7xDdAnjupgGG799XlbaunseOq4IVYNeosl23pSV8Tv0KPr1Z8q8Je/o=,iv:pQHQd5v2vT/s+OQOoebM6Kp3Q8qAeSelPGyzwrzD4zA=,tag:9l8DCC4mTBzDD9hZZO4H0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
