apiVersion: v1
kind: Secret
metadata:
    name: lidify-secrets
    namespace: media-stack
type: Opaque
stringData:
    last_fm_api_key: ENC[AES256_GCM,data:Vgh++J5xIzsDwGKF1Xz1a0X4vDUDATUXi0oBL4Kk23w=,iv:NLH/0tlC7BwijmXixnmOPpp0SV3GynBn6gNWnz4WbIk=,tag:CBInV5cbh9WhWtIi75idgA==,type:str]
    last_fm_api_secret: ENC[AES256_GCM,data:Vg36rVsgcaiTYaszR+4qAFH8SGZk/PAM5HqgBfH/hPs=,iv:yQKzib2SEgnXv2S7YrHYwNgBVRFnjtg7htv5hTr/aik=,tag:fH55JKdyxfmD81i/zV5amA==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZWhUL3g0allxMEFZNzFa
            WElRdFdDb1ZreHpWR3FWTjhHVWFhcnZOYXc0CkhBWEFTR2R4RkIxTkdSZVBhcVpW
            dDNOaUNPYzB3cjdleHNBTExKbm55TkEKLS0tIGhOMDBEQmpxa3FmdHFPOFlOSHhK
            VWxVSUNTemVYSjRJaVJXTnp0RHdZZFUKUfzt4LZgp03eX3E+THihHZH+XziySlOp
            fFgfmF71TmKc2gbFU+3Lq4+fD1Z5FsqFYHBa/RZanYDth7UJ16iKqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T15:19:10Z"
    mac: ENC[AES256_GCM,data:jQbdMB4G8gaZqJYMxUeX8R4b3vmOUuvhmqN7tReCFdK/eBhCb6jlrrGpvHrYgxJYZpApdjH/cs10d4b3aBvWGyWj4P67bSQ/b5i9Y+E7/brZCRBfJHt/ALH1i2Vw+SuNesTBBnnM61+fojxvvk07M6EAOFYLu7W4TvgD7iGn5cw=,iv:CHszDjM75IIXIPv+zVikP7QCERAAlvD1rAqRaeW1pe0=,tag:JtozlupebOS/V+6NnGvsZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
