apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-stoneblock4-server
  namespace: minecraft
spec:
  interval: 30m
  timeout: 30m
  chart:
    spec:
      chart: minecraft
      version: '5.1.1'
      sourceRef:
        kind: HelmRepository
        name: minecraft-server
        namespace: minecraft
  valuesFrom:
    - kind: ConfigMap
      name: minecraft-stoneblock4-values
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3