apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 37.x
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 192.168.0.200
      annotations:
        metallb.io/address-pool: default