apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 37.x
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: CF_API_TOKEN
    podSecurityContext:
      fsGroup: 65532
    additionalArguments:
      - "--certificatesresolvers.myresolver.acme.email=admin@pxldi.de"
      - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.delaybeforecheck=0"
      - "--certificatesresolvers.myresolver.acme.keytype=RSA4096"
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 192.168.0.200
      annotations:
        metallb.io/address-pool: default

    ingressClass:
      enabled: true
      name: traefik
      isDefaultClass: true

    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
        ingressClass: traefik

    entrypoints:
      web:
        address: ":80"
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        address: ":443"
        http:
          tls:
            enabled: true
    persistence:
      enabled: true
      name: traefik
      accessMode: ReadWriteOnce
      size: 1Gi
      path: /data
      storageClass: longhorn
      defaultMode: 0600