apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 37.x
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    env:
      - name: CLOUDFLARE_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: CF_API_TOKEN
    podSecurityContext:
      fsGroup: 65532
    additionalArguments:
      - "--certificatesresolvers.myresolver.acme.email=admin@pxldi.de"
      - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.delaybeforecheck=0"
      - "--certificatesresolvers.myresolver.acme.keytype=RSA4096"
      - "--api.dashboard=true"
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIP: 192.168.0.200
      annotations:
        metallb.io/address-pool: default

    ports:
      traefik:
        port: 8080
        expose:
          default: true
        exposedPort: 8080
        protocol: TCP
      web:
        port: 80
        expose:
          default: true
        exposedPort: 80
        protocol: TCP
        redirections:
          entryPoint:
            to: websecure
            scheme: https
      websecure:
        port: 443
        expose:
          default: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true

    ingressClass:
      enabled: true
      name: traefik
      isDefaultClass: true

    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
        ingressClass: traefik

    ingressRoute:
      dashboard:
        enabled: true
        matchRule: "PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
        entryPoints: ["websecure"]
        services:
          - name: api@internal
            kind: TraefikService
        tls:
          certResolver: myresolver
        middlewares:
          - name: authelia-forwardauth
            namespace: traefik
    persistence:
      enabled: true
      name: traefik-acme
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: longhorn
      path: /data
      #type: pvc
      #name: traefik
      #accessMode: ReadWriteOnce
      #size: 1Gi
      #path: /data
      #storageClass: longhorn
      #defaultMode: 0600