apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-middleware-reader
rules:
  # legacy CRDs
  - apiGroups: ["traefik.containo.us"]
    resources:
      - middlewares
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - tlsoptions
      - tlsstores
      - traefikservices
    verbs: ["get", "list", "watch"]
  # new CRDs used after v3 upgrades
  - apiGroups: ["traefik.io"]
    resources:
      - middlewares
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - tlsoptions
      - tlsstores
      - traefikservices
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-middleware-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-middleware-reader
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: traefik