---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-config
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-dual-disk
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-downloads
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soulsync-config
  namespace: music
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-dual-disk
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soulsync-data
  namespace: music
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-dual-disk
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soulsync-logs
  namespace: music
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 5Gi