apiVersion: apps/v1
kind: Deployment
metadata:
  name: slskd
  namespace: media-stack
  labels:
    app: slskd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: slskd
  template:
    metadata:
      labels:
        app: slskd
    spec:
      containers:
      # Gluetun VPN sidecar
      - name: gluetun
        image: qmcgaw/gluetun:latest
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        env:
        - name: VPN_SERVICE_PROVIDER
          value: "custom"
        - name: VPN_TYPE
          value: "wireguard"
        - name: FIREWALL_INPUT_PORTS
          value: "5030"
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "192.168.0.0/16,10.0.0.0/8"
        - name: TZ
          value: "Europe/Berlin"
        ports:
        - containerPort: 8888
          name: http-proxy
        volumeMounts:
        - name: wireguard-config
          mountPath: /gluetun/wireguard
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      
      # Slskd main container
      - name: slskd
        image: slskd/slskd:latest
        env:
        - name: SLSKD_HTTP_PORT
          value: "5030"
        - name: SLSKD_HTTPS_PORT
          value: "5031"
        - name: SLSKD_SLSK_LISTEN_PORT
          value: "50300"
        - name: SLSKD_NO_AUTH
          value: "true"
        - name: SLSKD_SLSK_USERNAME
          valueFrom:
            secretKeyRef:
              name: music-config
              key: SLSKD_SLSK_USERNAME
        - name: SLSKD_SLSK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: music-config
              key: SLSKD_SLSK_PASSWORD
        - name: SLSKD_REMOTE_CONFIGURATION
          value: "true"
        volumeMounts:
        - name: config
          mountPath: /app
        - name: downloads
          mountPath: /app/downloads
        - name: music
          mountPath: /music
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
      
      volumes:
      - name: wireguard-config
        secret:
          secretName: music-config
      - name: config
        persistentVolumeClaim:
          claimName: slskd-config
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-pvc
      - name: music
        persistentVolumeClaim:
          claimName: music-library
      
      shareProcessNamespace: true