apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 12h
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      version: ">=1.88.0"
  values:
    rbac:
      create: true
      createClusterRoles: true
  valuesFrom:
    - kind: Secret
      name: operator-oauth
      valuesKey: client_id
      targetPath: oauth.clientId
    - kind: Secret
      name: operator-oauth
      valuesKey: client_secret
      targetPath: oauth.clientSecret