apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: "0.15.2"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    speaker:
      rbac:
        create: true
      nodeSelector: {}
      tolerations: []
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 999
      resources: {}

    controller:
      rbac:
        create: true
      nodeSelector: {}
      tolerations: []
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 999
      resources: {}