---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  settings.yaml: |
    title: Homelab
    background:
      image: https://images.unsplash.com/photo-1526992356629-fbf40452d54d?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1773
      blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
    favicon: "https://raw.githubusercontent.com/pxldi/homelab/refs/heads/main/flux/apps/homepage/resources/house-icon.png"
    theme: dark
    color: cyan

    useEqualHeights: true
    cardBlur: xl
    headerBlur: xl

    debug: true

    headerStyle: boxed
    hideVersion: true

    statusStyle: "dot"

    layout:
      Infra:
          style: columns
      Media:
        style: columns
        #columns: 5
      Apps:
        style: columns
  kubernetes.yaml: |
    mode: cluster
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        
    - resources:
        label: Disks
        expanded: true
        disk:
          - /mnt/nvme
          - /mnt/hdd1
          - /mnt/hdd2

    - search:
        provider: duckduckgo
        target: _blank
    
    - datetime:
        text_size: xl
        format:
          timeStyle: short
    
    - openmeteo:
        label: {{HOMEPAGE_VAR_CITY_NAME_ENV}}
        latitude: {{HOMEPAGE_VAR_CITY_LATITUDE_ENV}}
        longitude: {{HOMEPAGE_VAR_CITY_LONGITUDE_ENV}}
        units: metric
        cache: 5
  services.yaml: |
    - Infra:
      - Traefik:
          icon: traefik.png 
          href: https://traefik.pxldi.de
          description: Traefik Dashboard
          widget:
            type: traefik
            url: http://traefik.traefik:8080

    - Media:
      - Sonarr:
          icon: sonarr.png
          href: https://sonarr.pxldi.de
          description: TV Shows
          widget:
            type: sonarr
            url: http://sonarr.sonarr:8989
            key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
            enableQueue: true

    - Apps:
      - Grafana:
          icon: grafana.png
          href: https://grafana.pxldi.de
          description: Metrics Dashboard
          widget:
            type: grafana
            version: 2
            url: http://kube-prometheus-stack-grafana.monitoring:80
            username: {{HOMEPAGE_VAR_GRAFANA_USER}}
            password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
  bookmarks.yaml: ""
  docker.yaml: ""
  custom.css: ""
  custom.js: ""