apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  services.yaml: |
    ---
    - Media:
        - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin.yourdomain.com
            description: Media server
            widget:
              type: jellyfin
              url: http://jellyfin.jellyfin.svc.cluster.local:8096
              key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
        
        - Immich:
            icon: immich.png
            href: https://immich.yourdomain.com
            description: Photo management
            widget:
              type: immich
              url: http://immich.immich.svc.cluster.local:2283
              key: {{HOMEPAGE_VAR_IMMICH_API_KEY}}
    
    - Tools:
        - Obsidian LiveSync:
            icon: obsidian.png
            href: https://obsidian.yourdomain.com
            description: Note synchronization
        
    - Infrastructure:
        - Flux:
            icon: flux-cd.png
            href: https://github.com/yourusername/homelab
            description: GitOps
            widget:
              type: flux
              cluster: homelab
        
        - Kubernetes:
            icon: kubernetes.png
            href: https://k8s.yourdomain.com
            description: Cluster dashboard
            widget:
              type: kubernetes
              cluster:
                show: true
                cpu: true
                memory: true
                showLabel: true
  
  widgets.yaml: |
    ---
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    
    - resources:
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true
    
    - search:
        provider: google
        target: _blank
    
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
  
  bookmarks.yaml: |
    ---
    - Developer:
        - GitHub:
            - icon: github.png
              href: https://github.com/yourusername/homelab
              description: Homelab repo
        
        - Flux:
            - icon: flux-cd.png
              href: https://fluxcd.io/docs/
              description: Flux documentation
    
    - Homelab:
        - Talos:
            - icon: talos.png
              href: https://www.talos.dev/
              description: Talos documentation
        
        - Renovate:
            - icon: renovate.png
              href: https://docs.renovatebot.com/
              description: Renovate docs
  
  settings.yaml: |
    ---
    title: Homelab
    favicon: https://cdn-icons-png.flaticon.com/512/2917/2917995.png
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      Media:
        style: row
        columns: 3
      Tools:
        style: row
        columns: 2
      Infrastructure:
        style: row
        columns: 2
    
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system.svc.cluster.local
  
  kubernetes.yaml: |
    ---
    mode: cluster