apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  services.yaml: |
    ---
    - Media:
        - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin.pxldi.de
            description: Media server
            widget:
              type: jellyfin
              url: http://jellyfin.jellyfin.svc.cluster.local:8096
              key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
        
        - Immich:
            icon: immich.png
            href: https://immich.pxldi.de
            description: Photo management
            widget:
              type: immich
              url: http://immich.immich.svc.cluster.local:2283
              key: {{HOMEPAGE_VAR_IMMICH_API_KEY}}
        
    - Infrastructure:
        - Flux:
            icon: flux-cd.png
            href: https://github.com/pxldi/homelab
            description: GitOps
            widget:
              type: flux
              cluster: homelab
  
  widgets.yaml: |
    ---
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    
    - resources:
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true
    
    - search:
        provider: google
        target: _blank
    
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
  
  settings.yaml: |
    ---
    title: Homelab
    favicon: https://cdn-icons-png.flaticon.com/512/2917/2917995.png
    theme: dark
    color: slate
    headerStyle: boxed
    layout:
      Media:
        style: row
        columns: 3
      Tools:
        style: row
        columns: 2
      Infrastructure:
        style: row
        columns: 2
    
    providers:
      longhorn:
        url: http://longhorn-frontend.longhorn-system.svc.cluster.local
  
  kubernetes.yaml: |
    ---
    mode: cluster