---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  settings.yaml: |
    title: Platform
    favicon: ""
    theme: dark
    color: slate
    background:
      image: https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
      blur: sm
      opacity: 70
    layout:
      Kubernetes:
      Cloud:
      Network:
      Storage:
      Monitoring:
      Analytics:
  kubernetes.yaml: |
    mode: cluster
  widgets.yaml: ""
  services.yaml: ""
  bookmarks.yaml: ""
  docker.yaml: ""
  custom.css: ""
  custom.js: ""