---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  settings.yaml: |
    title: Platform
    favicon: ""
    theme: dark
    color: slate
    background:
      image: https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
      blur: sm
      opacity: 70
    layout:
      Kubernetes:
      Cloud:
      Network:
      Storage:
      Monitoring:
      Analytics:
  kubernetes.yaml: |
    mode: cluster
  widgets.yaml: |
    - datetime:
        text_size: xl
        format:
          timeStyle: short

    - openmeteo:
        label: $CITY_NAME_ENV
        latitude: $CITY_LATITUDE_ENV
        longitude: $CITY_LONGITUDE_ENV
        timezone: Europe/Berlin
        units: metric
        cache: 5
        format:
          maximumFractionDigits: 1

    - resources:
        label: Cluster
        kubernetes:
          cluster:
            show:
              - cpu
              - memory
              - nodes
          nodes:
            show:
              - cpu
              - memory

  services.yaml: |
    - Kubernetes:
      - Traefik:
          icon: traefik
          href: https://traefik.pxldi.de
          server: traefik
          namespace: traefik
          container: traefik
      - Longhorn:
          icon: longhorn
          href: https://longhorn.pxldi.de
          server: longhorn-ui
          namespace: longhorn-system
          container: longhorn-ui

    - Media:
        - Radarr:
            icon: radarr
            href: https://radarr.pxldi.de
            server: radarr
            namespace: media-stack
            container: radarr
        - Sonarr:
            icon: sonarr
            href: https://sonarr.pxldi.de
            server: sonarr
            namespace: media-stack
            container: sonarr
        - Sabnzbd:
            icon: sabnzbd
            href: https://sabnzbd.pxldi.de
            server: sabnzbd
            namespace: media-stack
            container: sabnzbd
        - Jellyfin:
            icon: jellyfin
            href: https://jellyfin.pxldi.de
            server: jellyfin
            namespace: media-stack
            container: jellyfin

    - Network:
        - Pi-hole:
            icon: pi-hole
            href: https://pihole.pxldi.de/admin
            server: pihole
            namespace: pihole
            container: pihole

  bookmarks.yaml: ""
  docker.yaml: ""
  custom.css: ""
  custom.js: ""