---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  settings.yaml: |
    title: Homelab
    background:
      image: https://images.unsplash.com/photo-1526992356629-fbf40452d54d?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=1773
      blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
    favicon: "https://raw.githubusercontent.com/pxldi/homelab/refs/heads/main/flux/apps/homepage/resources/house-icon.png"
    theme: dark
    color: cyan

    useEqualHeights: true
    cardBlur: xl
    headerBlur: xl

    debug: true

    headerStyle: boxed
    hideVersion: true

    statusStyle: "dot"

    providers:
      finnhub: {{HOMEPAGE_VAR_FH_API_KEY}}

    layout:
      Row1:
        header: false
        style: row
        columns: 3
      Row2:
        header: false
        style: row
        columns: 4
      Row3:
        header: false
        style: row
        columns: 3
      Row4:
        header: false
        style: row
        columns: 4
      Row5:
        header: false
        style: row
        columns: 4
      Row6:
        header: false
        style: row
        columns: 2
  kubernetes.yaml: |
    mode: cluster
  widgets.yaml: |
    - logo:
        icon: "https://raw.githubusercontent.com/pxldi/homelab/refs/heads/main/flux/apps/homepage/resources/house-icon.png"
    
    - resources:
        cpu: true
        memory: true
        
    - resources:
        label: Disks
        expanded: true
        disk:
          - /mnt/nvme
          - /mnt/hdd1
          - /mnt/hdd2
    
    - datetime:
        text_size: xl
        format:
          timeStyle: short
    
    - openmeteo:
        label: {{HOMEPAGE_VAR_CITY_NAME_ENV}}
        latitude: {{HOMEPAGE_VAR_CITY_LATITUDE_ENV}}
        longitude: {{HOMEPAGE_VAR_CITY_LONGITUDE_ENV}}
        units: metric
        cache: 5
  services.yaml: |
    - Row1:
      - Traefik:
          icon: traefik.png 
          href: https://traefik.pxldi.de
          ping: https://traefik.pxldi.de
          widget:
            type: traefik
            url: http://traefik.traefik:8080
      - Grafana:
          icon: grafana.png
          href: https://grafana.pxldi.de
          ping: https://grafana.pxldi.de
          widget:
            type: grafana
            version: 2
            url: http://kube-prometheus-stack-grafana.monitoring:80
            username: {{HOMEPAGE_VAR_GRAFANA_USER}}
            password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
      - Prometheus:
          icon: prometheus.png
          href: https://prometheus.pxldi.de
          ping: https://prometheus.pxldi.de
          widget:
            type: prometheus
            url: http://kube-prometheus-stack-prometheus.monitoring:9090

    - Row2:
      - Sabnzbd:
          icon: sabnzbd.png
          href: https://sabnzbd.pxldi.de
          ping: https://sabnzbd.pxldi.de
          widget:
            type: sabnzbd
            url: http://sabnzbd.media-stack:10097
            key: {{HOMEPAGE_VAR_SABNZBD_API_KEY}}
      - Sonarr:
          icon: sonarr.png
          href: https://sonarr.pxldi.de
          ping: https://sonarr.pxldi.de
          widget:
            type: sonarr
            url: http://sonarr.media-stack:8989
            key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
      - Radarr:
          icon: radarr.png
          href: https://radarr.pxldi.de
          ping: https://radarr.pxldi.de
          widget:
            type: radarr
            url: http://radarr.media-stack:7878
            key: {{HOMEPAGE_VAR_RADARR_API_KEY}}
      - Jellyfin:
          icon: jellyfin.png
          href: https://jellyfin.pxldi.de
          ping: https://jellyfin.pxldi.de
          widget:
            type: jellyfin
            url: http://jellyfin.media-stack:8096
            key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}
    
    - Row3:
      - Pihole:
          icon: pi-hole.png
          href: https://pihole.pxldi.de/admin/
          ping: https://pihole.pxldi.de/admin/
          widget:
            type: pihole
            url: http://pihole-web.pihole:80
            version: 6
      - Tandoor:
          icon: tandoor-recipes.png
          href: https://recipes.pxldi.de/
          ping: https://recipes.pxldi.de/
          widget:
            type: tandoor
            url: http://tandoor.tandoor:80
            key: {{HOMEPAGE_VAR_TANDOOR_API_KEY}}
      - Nextcloud:
          icon: nextcloud.png
          href: https://nextcloud.pxldi.de/
          ping: https://nextcloud.pxldi.de/
          widget:
            type: nextcloud
            url: https://nextcloud.pxldi.de
            key: {{HOMEPAGE_VAR_NEXTCLOUD_API_KEY}}
            fields: ["freespace", "activeusers", "numfiles", "numshares"]

    - Row4:
      - Homelab Repo:
          icon: github.png
          href: https://github.com/pxldi/homelab
      - FluxCD Docs:
          icon: flux-cd.png
          href: https://fluxcd.io/flux/
      - Cloudflare Dashboard:
          icon: cloudflare.png
          href: https://dash.cloudflare.com
      - Dashboard Icons:
          icon: dashboard-icons.png
          href: https://dashboardicons.com/

    - Row5:
      - HomeAssistant:
          icon: home-assistant.png
      - Kavita:
          icon: kavita.png
      - SearXNG:
          icon: searxng.png
      - Overleaf:
          icon: overleaf.png
    
    - Row6:
      - Stocks:
          icon: google-finance.png
          widget:
            type: stocks
            provider: finnhub
            watchlist:
              - NVDA
              - AAPL
              - MSFT
              - AMZN
              - AMD
      - Crypto:
          icon: bitcoin.png
          widget:
            type: coinmarketcap
            currency: USD
            symbols: [BTC, ETH, XRP, SOL, DOGE]
            key: {{HOMEPAGE_VAR_CMC_API_KEY}}
            defaultinterval: 7d

  bookmarks.yaml: ""
  docker.yaml: ""
  custom.css: |
    #widgets-wrap {
      justify-content: center !important;
      gap: 1.5rem !important;
    }
    
    #information-widgets-right {
      justify-content: center !important;
      margin: 0 !important;
    }
    
    .widget-container {
      margin: 0 !important;
    }
  custom.js: |
    const RELOAD_BUTTON_SELECTORS = [
      "#revalidate",
      '[data-testid="revalidate"]',
      ".reload-button",
      'button[aria-label="Reload"]',
    ];

    function removeReloadButton() {
      RELOAD_BUTTON_SELECTORS.forEach((selector) => {
        document.querySelectorAll(selector).forEach((el) => el.remove());
      });
    }

    function setupReloadButtonObserver() {
      const observer = new MutationObserver(() => removeReloadButton());
      observer.observe(document.body, {
        childList: true,
        subtree: true,
      });
      return observer;
    }

    document.addEventListener("DOMContentLoaded", removeReloadButton);
    window.addEventListener("load", () => {
      removeReloadButton();
      setupReloadButtonObserver();
      [100, 500, 1000].forEach((delay) => setTimeout(removeReloadButton, delay));
    });