apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: monsterrr
        namespace: flux-system
  values:
    enableRbac: true
    serviceAccount:
      create: true
      name: homepage
    
    service:
      main:
        ports:
          http:
            port: 3000
    
    ingress:
      main:
        enabled: true
        ingressClassName: tailscale
        hosts:
          - host: homepage
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - homepage
    
    config:
      useExistingConfigMap: homepage-config
    
    envFrom:
      - secretRef:
          name: homepage-secret
    
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    persistence:
      logs:
        enabled: true
        storageClass: longhorn
        size: 10Gi