apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: monsterrr
        namespace: flux-system
  values:
    enableRbac: true
    serviceAccount:
      create: true
      name: homepage

    service:
      main:
        ports:
          http:
            port: 3000

    config:
      allowedHosts:
        - "homepage.pxldi.de"

    envFrom:
      - secretRef:
          name: homepage-secret

    volumes:
      - name: homepage-config
        configMap:
          name: homepage
      - name: homepage-custom
        emptyDir: {}

    initContainers:
      - name: copy-config
        image: busybox:1.36
        command: ["sh", "-c", "cp /configmap/* /custom/"]
        volumeMounts:
          - name: homepage-config
            mountPath: /configmap
          - name: homepage-custom
            mountPath: /custom

    extraVolumeMounts:
      - name: homepage-custom
        mountPath: /app/config