apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controllers:
      homepage:
        replicas: 1
        serviceAccount:
          create: false
          name: homepage
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.5.0
            env:
              - name: TZ
                value: Etc/UTC
              - name: HOMEPAGE_ALLOWED_HOSTS
                value: homepage.pxldi.de
              - name: HOMEPAGE_VAR_CITY_NAME_ENV
                valueFrom:
                  secretKeyRef:
                    name: homepage-secret
                    key: CITY_NAME
              - name: HOMEPAGE_VAR_CITY_LATITUDE_ENV
                valueFrom:
                  secretKeyRef:
                    name: homepage-secret
                    key: CITY_LATITUDE
              - name: HOMEPAGE_VAR_CITY_LONGITUDE_ENV
                valueFrom:
                  secretKeyRef:
                    name: homepage-secret
                    key: CITY_LONGITUDE
              - name: HOMEPAGE_VAR_GRAFANA_USER
                valueFrom:
                  secretKeyRef:
                    name: homepage-secret
                    key: GRAFANA_USER
              - name: HOMEPAGE_VAR_GRAFANA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: homepage-secret
                    key: GRAFANA_PASSWORD
              - name: HOMEPAGE_VAR_RADARR_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: homepage-secret
                    key: RADARR_API_KEY
              - name: HOMEPAGE_VAR_SONARR_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: homepage-secret
                    key: SONARR_API_KEY
              - name: HOMEPAGE_VAR_SABNZBD_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: homepage-secret
                    key: SABNZBD_API_KEY
              - name: HOMEPAGE_VAR_JELLYFIN_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: homepage-secret
                    key: JELLYFIN_API_KEY
              - name: HOMEPAGE_VAR_PIHOLE_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: homepage-secret
                    key: PIHOLE_API_KEY
              - name: HOMEPAGE_VAR_TANDOOR_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: homepage-secret
                    key: TANDOOR_API_KEY
              - name: HOMEPAGE_VAR_NEXTCLOUD_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: homepage-secret
                    key: NEXTCLOUD_API_KEY
            envFrom:
              - secretRef:
                  name: homepage-secret
            probes:
              liveness:
                enabled: true
                path: /
                port: 3000
              readiness:
                enabled: true
                path: /
                port: 3000
    service:
      app:
        controller: homepage
        ports:
          http:
            port: 3000
    ingress:
      app:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-authelia-forwardauth@kubernetescrd
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
        hosts:
          - host: homepage.pxldi.de
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - homepage.pxldi.de
    persistence:
      config:
        type: configMap
        name: homepage
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
      hdd1:
        type: hostPath
        hostPath: /var/mnt/hdd1
        hostPathType: Directory
        globalMounts:
          - path: /mnt/hdd1
            readOnly: true
      
      hdd2:
        type: hostPath
        hostPath: /var/mnt/hdd2
        hostPathType: Directory
        globalMounts:
          - path: /mnt/hdd2
            readOnly: true
      
      nvme:
        type: hostPath
        hostPath: /var
        hostPathType: Directory
        globalMounts:
          - path: /mnt/nvme
            readOnly: true