apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  template:
    spec:
      containers:
        - name: homepage
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "*.ts.net,localhost,127.0.0.1"