apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: homepage
            patch: |-
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: HOMEPAGE_ALLOWED_HOSTS
                  value: "*.ts.net,localhost,127.0.0.1"